# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import computeandstorage_pb2 as computeandstorage__pb2


class EC2OperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreData = channel.unary_unary(
                '/computeandstorage.EC2Operations/StoreData',
                request_serializer=computeandstorage__pb2.StoreRequest.SerializeToString,
                response_deserializer=computeandstorage__pb2.StoreReply.FromString,
                )
        self.AppendData = channel.unary_unary(
                '/computeandstorage.EC2Operations/AppendData',
                request_serializer=computeandstorage__pb2.AppendRequest.SerializeToString,
                response_deserializer=computeandstorage__pb2.AppendReply.FromString,
                )
        self.DeleteFile = channel.unary_unary(
                '/computeandstorage.EC2Operations/DeleteFile',
                request_serializer=computeandstorage__pb2.DeleteRequest.SerializeToString,
                response_deserializer=computeandstorage__pb2.DeleteReply.FromString,
                )


class EC2OperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EC2OperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreData': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreData,
                    request_deserializer=computeandstorage__pb2.StoreRequest.FromString,
                    response_serializer=computeandstorage__pb2.StoreReply.SerializeToString,
            ),
            'AppendData': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendData,
                    request_deserializer=computeandstorage__pb2.AppendRequest.FromString,
                    response_serializer=computeandstorage__pb2.AppendReply.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=computeandstorage__pb2.DeleteRequest.FromString,
                    response_serializer=computeandstorage__pb2.DeleteReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'computeandstorage.EC2Operations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EC2Operations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/computeandstorage.EC2Operations/StoreData',
            computeandstorage__pb2.StoreRequest.SerializeToString,
            computeandstorage__pb2.StoreReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AppendData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/computeandstorage.EC2Operations/AppendData',
            computeandstorage__pb2.AppendRequest.SerializeToString,
            computeandstorage__pb2.AppendReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/computeandstorage.EC2Operations/DeleteFile',
            computeandstorage__pb2.DeleteRequest.SerializeToString,
            computeandstorage__pb2.DeleteReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
